In [19]:
import MySQLdb

# 打开数据库连接
db = MySQLdb.connect("localhost", "root", "btstest", "innovation", charset='utf8' )

# 使用cursor()方法获取操作游标 
cursor = db.cursor()

# 使用execute方法执行SQL语句
cursor.execute("SELECT VERSION()")

# 使用 fetchone() 方法获取一条数据
data = cursor.fetchone()

print "Database version : %s " % data


cursor.execute("DROP TABLE IF EXISTS point_progress")

# # 创建数据表SQL语句
sql = """CREATE TABLE point_progress (
          squad  CHAR(45) NOT NULL,
          month  CHAR(45) NOT NULL,
          approve_plan INT,  
          approve_actual INT,
          done_plan INT,
          done_actual INT,
          score_plan INT,
          score_actual INT)"""

cursor.execute(sql)

# 关闭数据库连接

values = [
('squad_1', 'Apr', 0, 0, 0,  0, 0, 0),\
('squad_2', 'Apr', 2, 2, 0,  1, 2, 4),\
('squad_3', 'Apr', 0, 0, 0,  0, 0, 0),\
('squad_4','Apr',  1, 1, 0,  1, 1, 3),\
('squad_5','Apr',  1, 0, 0,  0, 1, 0),\
('squad_6','Apr',  1, 1, 0,  0, 1, 1),\
('squad_7','Apr',  0, 0, 0,  0, 0, 0),\
('squad_8','Apr',  1, 0, 0, 0,  1, 0),\
('squad_9','Apr',  1, 1, 0, 0, 1,  1),\
('squad_10','Apr', 1, 2, 0, 0, 1,  2),\
('squad_11','Apr', 1, 1, 1, 0, 3,  1),\
('squad_12','Apr', 0, 0, 0, 0, 0,  0)]



# SQL 插入语句
for value in values:
    sql = "INSERT INTO point_progress(squad, month, approve_plan, approve_actual, done_plan, done_actual, score_plan, score_actual) \
           VALUES ('%s', '%s', '%d', '%d', '%d', '%d', '%d', '%d')" % (value)
    try:
       # 执行sql语句
       cursor.execute(sql)
       # 提交到数据库执行
       db.commit()
    except Exception, e:
       # 发生错误时回滚
       print '++++', e
       db.rollback()



db.close()

Database version : 5.7.20-log 


1. 找数字

    难度：*


​ 一年一度的国际猜谜语大会上，你认识了一个非常棒的朋友，你请求问他(她)要个电话号码，以便保持联系。他(她)冲你微微一笑，转身离去。第二天你发现在你的酒店房间的门下面有一张便签，上面写着：

亲爱的，朋友

​ 我已经用大写字母拼写的英文数字("ZERO", "ONE", "TWO", "THREE", "FOUR", "FIVE", "SIX", "SEVEN", "EIGHT", "NINE" )替换了我的电话号码中的每一个数字，然后我随机打乱了所有的字母的序列，生成了字符串S，你可以从字符串中算出我的电话号码。给你一个小的提示，我的电话号码是非递减的顺序组成的哦。如果你能解密出来，记得给我打电话哈。

​ 你很想打电话给你的这位朋友，并告诉他(她)这是一种非常讨厌的一种给别人电话号码的方式。但首先他要先破解了这串字符。
输入

第一行是测试向量的个数 T，第二行开始是T个测试向量，每行包含一个大写字母组成的字符串S，
输出

每一个测试向量输出一行内容Case #x: y，其中x是测试向量的序号（从1开始）, y是正确的电话号码
限制

1 ≤ T ≤ 100.
Small dataset

3 ≤ length of S ≤ 20.
Large dataset

3 ≤ length of S ≤ 2000.


Input                   Output 
4
OZONETOWER              Case #1: 012
WEIGHFOXTOURIST         Case #2: 2468
OURNEONFOE              Case #3: 114
ETHER                   Case #4: 3

a*zero + b*one + c*two +d*three + e*four +f*five + g*six +h*seven + i*eight + j*nine

In [ ]:
 a*zero + b*one + c*two +d*three + e*four +f*five + g*six +h*seven + i*eight + j*nine
a + b + 2*d + f + 2*h + i +j = count(e)
e +f = count(f)
i = count(g)
d + i = count(h)
f + g +i +j=count(i) 
b + h + 2*j = count(n)
a +b + c +e = count(o)
a + d + e = count(r)
g + h = count(s)
c + d + i = count(t)
e = count(u)
f + h = count(v)
c = count(w)
g = count(x)
a = count(z)


In [14]:
import numpy as np
string = "OZONETOWER".lower()

#string.count('o')
a= [[1, 1, 0, 2, 0, 1, 0, 2, 1, 1], [0,0,0,0,1,1,0,0,0,0], [0,0,0,0,0,0,0,0,1,0], [0,0,0,1,0,0,0,0,1,0], [0,0,0,0,0,1,1,0,1,1],\
    [0,1,0,0,0,0,0,1,0,2], [1,1,1,0,1,0,0,0,0,0], [1,0,0,1,1,0,0,0,0,0], [0,0,0,0,0,0,1,1,0,0], [0,0,1,1,0,0,0,0,1,0],\
    [0,0,0,0,1,0,0,0,0,0], [0,0,0,0,0,1,0,1,0,0], [0,0,1,0,0,0,0,0,0,0], [0,0,0,0,0,0,1,0,0,0],[1,0,0,0,0,0,0,0,0,0]]

b= np.array(a)
print b

c= [string.count('e'), string.count('f'), string.count('g'), string.count('h'), string.count('i'), string.count('n'), string.count('o'),\
   string.count('r'), string.count('s'), string.count('t'), string.count('u'), string.count('v'), string.count('w'), string.count('x'),\
     string.count('z')]

d = np.array(c)
print d

x = np.linalg.solve(b, d)


print x

[[1 1 0 2 0 1 0 2 1 1]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0 1 0]
 [0 0 0 0 0 1 1 0 1 1]
 [0 1 0 0 0 0 0 1 0 2]
 [1 1 1 0 1 0 0 0 0 0]
 [1 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0]
 [0 0 1 1 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]]
[2 0 0 0 0 1 3 1 0 1 0 0 1 0 1]


LinAlgError: Last 2 dimensions of the array must be square

In [ ]:
 a*zero + b*one + c*two +d*three + e*four +f*five + g*six +h*seven + i*eight + j*nine
a + b + 2*d + f + 2*h + i +j = count(e)
e +f = count(f)
i = count(g)
d + i = count(h)
f + g +i +j=count(i) 
b + h + 2*j = count(n)
a +b + c +e = count(o)
a + d + e = count(r)
g + h = count(s)
c + d + i = count(t)
e = count(u)
f + h = count(v)
c = count(w)
g = count(x)
a = count(z)    
-------------------------------------------------
b + 2*d + f + 2*h  +j = count(e) -count(g) - count(z) 
f = count(f) - count(u)
d  = count(h) - count(g)
f  +j=count(i) - count(g) - count(x)
b + h + 2*j = count(n)
b  = count(o) - count(z) - count(w) - count(u)
d = count(r) - count(z) - count(u)
h = count(s) - count(x)
d  = count(t) - count(g) - count(w)
f + h = count(v)

----------
a = count(z)
b  = count(o) - count(z) - count(w) - count(u)
c = count(w)
d = count(r) - count(z) - count(u)
e = count(u)
f = count(f) - count(u)
g = count(x)
h = count(v) - count(f) - count(u)
i = count(g)
2j = count(n) - (count(o) - count(z) - count(w) - count(u)) - (count(v) - count(f) - count(u))
j= (count(n) - count(o) + count(z) + count(w) + 2*count(u) - count(v) + count(f))/2
-------------------------------------------------
# b + 2*d + f + 2*h  +j = count(e) - count(g) - count(z)
# f = count(f) - count(u)
# d  = count(h) - count(g)
# f +j=count(i) - count(g) - count(x) 
# b + h + 2*j = count(n)
# b   = count(o) - count(u) - count(w) - count(z)
# d  = count(r) - count(u) - count(z)
# g + h = count(s)
# c + d  = count(t) - count(g)
# f + h = count(v)


In [25]:
import numpy as np
string = "OZONETOWER".lower()

#string.count('o')
a= [[0, 1, 0, 2, 0, 1, 0, 2, 0, 1], [0,0,0,0,0,1,0,0,0,0], [0,0,0,1,0,0,0,0,0,0], [0,0,0,0,0,1,0,0,0,1], [0,1,0,0,0,0,0,1,0,2],\
    [0,1,0,0,0,0,0,0,0,0], [0,0,0,1,0,0,0,0,0,0], [0,0,0,0,0,0,0,1,0,0], [0,0,0,1,0,0,0,0,0,0], [0,0,0,0,0,1,0,1,0,0]]

b= np.array(a)
print b

c= [string.count('e')-string.count('g')-string.count('z'), string.count('f')-string.count('u'), string.count('h')-string.count('g'), \
    string.count('i')-string.count('g')- string.count('x'), string.count('n'), string.count('o')-string.count('z')-string.count('w')-string.count('u'),\
   string.count('r')-string.count('u')-string.count('z'), string.count('s')-string.count('x'), string.count('t')-string.count('g')-string.count('w'), string.count('v')]

d = np.array(c)
print d

x = np.linalg.solve(b, d) #np.dot(b, d)

print '012'
print x

[[0 1 0 2 0 1 0 2 0 1]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 1]
 [0 1 0 0 0 0 0 1 0 2]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0]]
[1 0 0 0 1 1 0 0 0 0]


LinAlgError: Singular matrix

In [24]:
# x + y + z = 6
# 2y + 5z = -4
# 2x + 5y - z = 27
import numpy as np
a =[[1, 1, 1], [0, 2, 5], [2, 5, -1]]
b= np.array(a)
c=[6, -4, 27]
d=np.array(c)
print b, d
x = np.linalg.solve(b, d)
print x




[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]] [ 6 -4 27]
[ 5.  3. -2.]


In [35]:
#string = "OZONETOWER".lower()
string = "ETHER ".lower()
def count(char):
    return string.count(char)

a = count('z')
b  = count('o') - count('z') - count('w') - count('u')
c = count('w')
d = count('r') - count('z') - count('u')
e = count('u')
f = count('f') - count('u')
g = count('x')
h = count('s') - count('x')#count('v') - count('f') - count('u')
i = count('g')
#f + g +i +j=count(i) 
j = count('i') -f -g -i  #(count('n') - count('o') + count('z') + count('w') + 2*count('u') - count('v') + count('f'))/2
print a, b, c, d, e, f, g, h, i, j

0 0 0 1 0 0 0 0 0 0
