In [1]:
def double_char(s):
    return  reduce(lambda x, y: x+y*2, s, "")

a = double_char("heLlo china")
print a

hheeLLlloo  cchhiinnaa


In [32]:
class FatherA(object):

    def __init__(self):
        print 'init action in father class A'

 
class FatherB(object):

    def __init__(self):
        print 'init action in father class B'

class FatherC(object):

    def __init__(self):
        print 'init action in father class C'


class SubClass(FatherA, FatherB, FatherC):

    def __init__(self):

        print 'init action in father class '
        [sub_class.__init__(self) for sub_class in SubClass.__bases__]
            #print sub_class
            #sub_class.__init__(self)
        #super(SubClass, self).__init__()
        print "init in subclass"

        
b = SubClass()

init action in father class 
init action in father class A
init action in father class B
init action in father class C
init in subclass


In [15]:
def double_char(s):
    return  reduce(lambda x, y: x+y.strip(x[-1]), s)

a = double_char("heeLllo cchinaa")
print a

heLlo china


In [4]:
x=[1,2,3]
y=[4,5,6]
a=[6,7,8]
b=[9,10,11]
xy=zip(x, y)
ab=zip(a, b)
print xy, ab
zip(*xy)





[(1, 4), (2, 5), (3, 6)] [(6, 9), (7, 10), (8, 11)]


[(1, 2, 3), (4, 5, 6)]

In [6]:
a=[1,2,3,4,5,6]
[x+10 for x in a]
[12]* 5


[11, 12, 13, 14, 15, 16]

In [ ]:
s = "good_morning"
print s[5:-1]
a = range(1,6,2)
print a

In [8]:
x, y =1, 2
min = x if x<y else y
print min

1


In [10]:
def wrap_info (f):
    b = {"b":20};
    def inner_func (*p, **k):
        print b['b'], p, k
        b['b'] += 1
        f(*p, **k)
    return inner_func

def info (s):
    print "func info: %s" % s


f1 = wrap_info (info)   #fl = innner_func
f1 ("a")                #inner_func('a')  20, a, {}   ;intfo('a'),  func info: a
f2 = wrap_info (info)   #f2 = inner_func
f1 ("b")                #innerf_func('b')  21, b, {} ; info('b'),    func info: b 
f2 ("c")                #20, c, func info: c


20 ('a',) {}
func info: a
21 ('b',) {}
func info: b
20 ('c',) {}
func info: c


In [5]:
class parent(object):
    def __init__(self):
        self.name = 'parent'
    def log(self):
        print 'log from %s' % self.name

class son(parent):
    def __init__(self):
        self.name = 'son'

    def log(self):
        print 'log from %s' % self.name
        
p = parent()
s = son()
parent.log(s)


        




log from parent


In [1]:
class Person(object):  
    def __init__(self,name,age,sex):  
        self.name=name  
        self.age= age  
        self.sex=sex  
    def disPlay(self):  
        print self.name  
        print self.age  
        print self.sex  
#Student inherit fromm Person           
class Student(Person):  
    def __init__(self, name, age, sex, gardon):  
        super(Student, self).__init__(name, age, sex)   #note:Please use parent class __init__ 
        self.gardon = gardon  
    def disPlay(self):              #note: Override display 
        #Person.disPlay(self)
        super(Student, self).disPlay()
        print self.gardon

stu1 = Student("zhangsan", 30, "man", "yanyi")   
stu1.disPlay()  


zhangsan
30
man
yanyi


In [ ]:
def operate_fun(a, b, oper):

    return float('%0.2f'%eval('{}{}{}'.format(float(a), oper, float(b))))

In [17]:
import numpy as npy  
from sklearn import linear_model, datasets  
from sklearn.cross_validation import train_test_split  
from sklearn.feature_extraction import DictVectorizer  
from sklearn.metrics import accuracy_score, classification_report  
  
iris = datasets.load_iris()  
X = iris.data[:, :2]  # we only take the first two features.  
Y = iris.target 

#print len(X)
#for n in range(150):  
#    print(X[n], Y[n])

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
logreg = linear_model.LogisticRegression(C=1e5, solver='lbfgs',multi_class='multinomial')
logreg.fit(X_train, y_train)
prediction = logreg.predict(X_test)  
print("accuracy score:")  
print(accuracy_score(y_test, prediction))  
print(classification_report(y_test, prediction))
      
class MyLogisticRegression:  

    def __init__(self, weights, constants, labels):  
        self.weights = weights  
        self.constants = constants  
        self.labels = labels  

    def predict_proba(self,X):  
        proba_list = []  
        len_label = len(self.labels)  
        for n in X: #.toarray():  
            pb = []  
            count = 0  
            for i in range(len_label):  
                value = npy.exp(npy.dot(n, self.weights[i]) + self.constants[i])  
                count = count + value  
                pb.append(value)  
            proba_list.append([x/count for x in pb])  
        return npy.asarray(proba_list)  

    def predict(self,X):  
        proba_list = self.predict_proba(X)  
        predicts = []  
        for n in proba_list.tolist():  
            i = n.index(max(n))  
            predicts.append(self.labels[i])  
        return npy.asarray(predicts)

print('\n')  
my_logreg = MyLogisticRegression(logreg.coef_, logreg.intercept_, logreg.classes_)  
my_logreg_proba = my_logreg.predict_proba(X_test)  
my_logreg_pred = my_logreg.predict(X_test)  
for index in range (5):  
    print(my_logreg_proba[index])  
    print("Predict label:", my_logreg_pred[index])  
    print("Correct label:", y_test[index])



accuracy score:
0.9
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        10
          1       0.88      0.78      0.82         9
          2       0.83      0.91      0.87        11

avg / total       0.90      0.90      0.90        30



[  8.86511141e-26   5.64775369e-01   4.35224631e-01]
('Predict label:', 1)
('Correct label:', 1)
[  9.99999942e-01   3.78533502e-08   2.02808786e-08]
('Predict label:', 0)
('Correct label:', 0)
[  9.92889672e-70   8.98623548e-02   9.10137645e-01]
('Predict label:', 2)
('Correct label:', 2)
[  4.40394869e-21   5.97659713e-01   4.02340287e-01]
('Predict label:', 1)
('Correct label:', 1)
[  5.68223856e-43   2.90652338e-01   7.09347662e-01]
('Predict label:', 2)
('Correct label:', 1)


In [44]:
def calculator_backup(data):
    total = 0
    data1=[[0,0] for i in xrange(12)]
    data1[:len(data)] = data
    for i in xrange(10):
        total += sum(data1[i]) 
        for i in xrange(sum(data1[i])/10 + data1[i][0]/10):
            total += sum(data1[i+1])
    print total
    
def calculator(data):
    total = 0
    data1=[[0,0] for i in xrange(12)]
    data1[:len(data)] = data
    for i in xrange(10):
        total = total + sum(data1[i])
        a=sum(data1[i+1]) for i in xrange(sum(data1[i])/10 + data1[i][0]/10)

    print total

test_1_data = [[10, 0], [10, 0], [10, 0], [10, 0], [10, 0], [10, 0],[10, 0],[10, 0], [10, 0], [10, 0], [10, 0], [10, 0],]
test_2_data = [[10, 0], [10, 0], [10, 0], [10, 0], [10, 0], [10, 0],[10, 0],[10, 0], [10, 0], [0, 0]]
test_3_data = [[9, 0], [9, 1], [10, 0], [10, 0], [10, 0], [10, 0],[10, 0],[10, 0], [10, 0], [0, 0]]

calculator(test_3_data)



#[sum(data[i]) + sum(data[i + sum(data[i])/10]) + sum(data[i + sum(data[i], data[i][0])/20*2])*sum(data[i], data[i][0])/20 for i in xrange(0, len(data)-2)]



SyntaxError: invalid syntax (<ipython-input-44-ad6964494e35>, line 17)

In [63]:
def calculator_book(data):
    tmp = list(data)
    print tmp
    for i in xrange(len(tmp)):
        tmp[i] = int(tmp[i])-1    
    print tmp
    
calculator_book('1233')
data = ['a', 'b', 'b', 'c', 'c', 'c', 'd', 'd', 'd']
from itertools import combinations
list_data = []
list(combinations(data, 2))

string_data = '1233'
total = 1000000
for a in xrange(0, 10):
    for b in xrange(0, 4):
        for c in xrange(0, 3):
            for d in xrange(0, 2):
                for e in xrange(0, 1):
                    if a+2*b+3*c+4*d+5*e==9:
                        tmp = 8*a + 0.95*8*2*b + 0.9*8*3*c +0.8*8*4*d +0.75*8*5*e
                        if tmp<total:
                            A,B,C,D,E=a,b,c,d,e
                            total = tmp
                        #print a, b, c, d, e
print '----', total, A,B,C,D,E

#a+b+c+d+e = sum（[int(i) for i in string_data])
#a=sum([int(i) for i in string_data])
#print a
#print 0<=a<=sum([int(i) for i in string_data])
#print len(string_data)*(len(string_data)-1)/2
#print 0<=b<=(len(string_data)*(len(string_data)-1)/2)
#print 0=<c<=9

A=['a']
B=['b', 'b']
C=['c', 'c', 'c']
D=['d', 'd', 'd']
E=[""]


def group():
    pass


# collections = set()
# for a in A:
#     for b in B:
#         for c in C:
#             for d in D:
#                 for e in E:
#                     collections.add(a+b+c+d+e)
#                     print a,b,c,d,e

# print collections


['1', '2', '3', '3']
[0, 1, 2, 2]
---- 62.4 0 1 1 1 0


In [ ]:
class Fib():
    def __init__(self):
        self.prev = 0
        self.curr = 1
 
    def __iter__(self):
        return self
 
    def next(self):
        return iter([1, 2, 3])
a=Fib()
next(a)
        
        
        
    



In [21]:
T=5
data=[11,12,13,14,21,23,24,31,33,34,41,42,43]
start, end=41, 14
import itertools
print '------------------'
ret = itertools.permutations(data)
for each_data in ret:
    if abs(each_data.index(14) - each_data.index(41))<=5:
        each_data_len=len(each_data)-1
        for index, ele in enumerate(each_data):
            value =  abs(each_data[index+1]-each_data[index])
            if value!=1 and value!=10:
                break
            if index==each_data_len:
                print 'yes'
                print each_data
                break
print '++++++'



------------------


KeyboardInterrupt: 

In [ ]:
import itertools
T=5
data1=[11,12,13,14,21,23,24,31,33,34,41,42,43]
print '------------------'
def find_data():
    data=[11,12,13,22,23,32,33,41,42]
    start_data, end_data=13, 41
    ret=itertools.permutations(data)
    for each_data in ret:
        end_index = each_data.index(end_data) 
        start_index = each_data.index(start_data)
        if start_index>end_index:
            start_index, end_index = end_index, start_index
        if abs(start_index - end_index)<=5:
            each_data_len=end_index-start_index-1 
            for index, ele in enumerate(each_data[start_index:end_index+1]):
                value =  abs(each_data[start_index+index+1]-each_data[start_index+index])
                if value!=1 and value!=10:
                    #print each_data
                    break
                if index==each_data_len:
                    print 'yes', each_data[index+1], each_data[index]
                    print each_data
                    return True
print '++++++++'

In [115]:
test_data="9/|8/|62|4-|-3|71|13|-/|4/|4/||4"
test_data = test_data.replace("||","|").replace("X", '100').replace('-/', '19').replace("-", '0').split("|")    

data=['00']*12; new_data = [[0, 0]]*12
data[0:len(test_data)] = test_data
data_tmp = [i.replace("/", str(10-int(i[0]))) for i in data]
print data_tmp
for i, j in enumerate(data_tmp):
    new_data[i]= int(j)/10, int(j)%10
print new_data

#total_list = [sum(new_data[i]) + sum(new_data[i + sum(new_data[i])/10]) + sum(new_data[i + sum(new_data[i], new_data[i][0])/20*2])*(sum(new_data[i], new_data[i][0])/20) for i in xrange(0, 10)]
total_list = [sum(new_data[i]) + (sum(new_data[i])/10)*(sum(new_data[i + sum(new_data[i])/10]) + sum(new_data[i + sum(new_data[i], new_data[i][0])/20*2])*(sum(new_data[i], new_data[i][0])/20)) for i in xrange(0, 10)]
print total_list
#print reduce(lambda x,y :  x+y, total_list,0)
#for each_data in test_data:
    #if "/" in each_data:
#    each_data = each_data.replace("/", str(10-int(each_data[0])))
    #print each_data
#    data.append(each_data)
#print data    

['91', '82', '62', '40', '03', '71', '13', '19', '46', '46', '4', '00']
[(9, 1), (8, 2), (6, 2), (4, 0), (0, 3), (7, 1), (1, 3), (1, 9), (4, 6), (4, 6), (0, 4), (0, 0)]
[20, 18, 8, 4, 3, 8, 4, 20, 20, 14]


In [ ]:
# -*- coding: utf-8 -*-
#test_data="9/|8/|62|4-|-3|71|13|-/|4/|4/||4"
test_data = "5/|5/|5/|5/|5/|5/|5/|5/|5/|5/||5 "

test_data = test_data.replace("||","|").replace("X", '100').replace('-/', '19').replace("-", '0').split("|")

data=['00']*12; new_data = [[0, 0]]*12
data[0:len(test_data)] = test_data
data_tmp = [i.replace("/", str(10-int(i[0]))) for i in data]
print data_tmp
for i, j in enumerate(data_tmp):
    new_data[i]= int(j)/10, int(j)%10
print new_data

#total_list = [sum(new_data[i]) + sum(new_data[i + sum(new_data[i])/10]) + sum(new_data[i + sum(new_data[i], new_data[i][0])/20*2])*(sum(new_data[i], new_data[i][0])/20) for i in xrange(0, 10)]
total_list = [sum(new_data[i]) + (sum(new_data[i])/10)*(sum(new_data[i + sum(new_data[i])/10]) + sum(new_data[i + sum(new_data[i], new_data[i][0])/20*2])*(sum(new_data[i], new_data[i][0])/20)) for i in xrange(0, 10)]
print total_list
print reduce(lambda x,y :  x+y, total_list,0)



In [112]:
# -*- coding: utf-8 -*-
#test_data="9/|8/|62|4-|-3|71|13|-/|4/|4/||4"
test_data = "9-|9-|9-|9-|9-|9-|9-|9-|9-|9-||"
test_data = "X|X|X|X|X|X|X|X|X|X||XX"
test_data = "5/|5/|5/|5/|5/|5/|5/|5/|5/|5/||5"
test_data = "X|7/|9-|X|-8|8/|-6|X|X|X||81"
edge_index = test_data.index("||") - test_data[:test_data.index("||")].count('|')
print edge_index

test_data = test_data.replace("-", '0').strip().split("|")
print test_data
data = []
[data.extend(list(i)) for i in test_data]
data = [i.replace("X", "10") for i in data]
print data

course_data = []
for index, each_data in enumerate(data):
     if "/" in each_data:
        course_data.append(10 - float(data[index-1]) + float(data[index+1]))
     if "10" in each_data  and index<edge_index and data[index+2]=="/":
        course_data.append(20)
     elif "10" in each_data and index<edge_index:
        course_data.append(10 + float(data[index+1]) +float(data[index+2]))
     elif "/" not in each_data:
        course_data.append(float(each_data))
print course_data
print data
print test_data.index("")
print int(reduce(lambda x,y :  float(x)+float(y), course_data[:edge_index],0))
#for index, each_node in enumerate(data):
#     if index==10:
#         break    
#     if "/" in each_node:
#         next_index =2 if index==9 else 1
#         current_value = 10 - float(data[index-1]) + float((data[index+next_index]).replace("X", '10'))
#         print '---',current_value
#     elif 'X' in each_node:
#         print each_node
#     else:
#         current_value = float(each_node)


#:
#def count_each_value(data):
#    if "/" or "X" in test_data:
#        return 10
#    else:
#        return int(data)
#for index, every_group in enumerate(test_data):
#    if 'X'==every_group:
#        current_value = count_each_valueQAt_each_value(every_group)    
#    current_value = count_each_value(every_group)
#    print "++++===", current_value
#for index, every_group in enumerate(test_data):
#    print '___', index
#    if index == 10:
#        break    
#    if "/" in every_group:
#        next_index = 2 if index==10 else 1
#        print '====',test_data[index+next_index][0].replace('X', 10)
#        current_value = 10 + int(test_data[index+next_index][0].replace('X', 10))
#    if "X" in every_group:
#        pass
#    print current_value
#    total_value += current_value
#print total_value
#data=['00']*12; new_data = [[0, 0]]*12
#data[0:len(test_data)] = test_data
#data_tmp = [i.replace("/", str(10-int(i[0]))) for i in data]
#print data_tmp


15
['X', '7/', '90', 'X', '08', '8/', '06', 'X', 'X', 'X', '', '81']
['10', '7', '/', '9', '0', '10', '0', '8', '8', '/', '0', '6', '10', '10', '10', '8', '1']
[20, 7.0, 12.0, 9.0, 0.0, 18.0, 0.0, 8.0, 8.0, 2.0, 0.0, 6.0, 30.0, 28.0, 19.0, 8.0, 1.0]
['10', '7', '/', '9', '0', '10', '0', '8', '8', '/', '0', '6', '10', '10', '10', '8', '1']
10
167


In [104]:
test_data = "9-|9-|9-|9-|9-|9-|9-|9-|9-|9-||"

def my_count(a, b=0, c=0):
    if a.isalpha()
        test_data
    if "/" in a:
        value = 10 + my_count()
count(test_data.split("|"))
#     if '/' in data:
#         value = 10 +  count()
#     if "-" in data:
#         value = int(data[0])
#     if 'X' in data:
#         value = 10 + count(next_data) + count()
        


['9-', '9-', '9-', '9-', '9-', '9-', '9-', '9-', '9-', '9-', '', '']


In [142]:
data = "53535341532333552421153122532224531451214533345121155451243411423124254253442345"

a_num = data.count("1")
b_num = data.count("2")
c_num = data.count("3")
d_num = data.count("4")
e_num = data.count("5")
print a_num,b_num, c_num, d_num,e_num
a_range= a_num + b_num + c_num + d_num + e_num
total = a_range*8
for a in xrange(0, a_range+1):
    for b in xrange(0, 11):        #5
        for c in xrange(0, 11):    #3
            for d in xrange(0, 16):    #3
                for e in xrange(0, 15):
                    if a+2*b+3*c +4*d+5*e == a_range and e+d<=15 and 14<e+d+c+b<=18 and c+d+e<=16 and a+b+c+d+e<=18:
                        tmp = 8*a + 0.95*8*2*b+0.9*8*3*c + 0.8*8*4*d + 0.75*8*5*e
                        if tmp<total:
                            A,B,C,D,E=a,b,c,d,e
                            total = tmp
                        #print a, b, c, d, e
print '----', total, A,B,C,D,E


14 16 17 15 18
---- 490.4 1 1 1 1 14


In [ ]:
pad = curses.newpad(100, 100)
#  These loops fill the pad with letters; this is
# explained in the next section
for y in range(0, 100):
    for x in range(0, 100):
        try: pad.addch(y,x, ord('a') + (x*x+y*y) % 26 )
        except curses.error: pass

#  Displays a section of the pad in the middle of the screen
pad.refresh( 0,0, 5,5, 20,75)




In [2]:
##old code like this
# if self.build_no.startswith('TL') or 'TDD' in self.build_no:
#             if tl_index == 1:
#                 build = abi_build
#             else:
#                 build = self.build_no
#         else:
#             if tl_index == 1:
#                 build = self.build_no
#             else:
#                 build = abi_build

def test(build_no, tl_index=1):
    abi_build = "abi_build"
    if build_no.startswith('TL') or 'TDD' in build_no:
        if tl_index == 1:
            build = abi_build
        else:
            build = build_no
    else:
        if tl_index == 1:
            build = build_no
        else:
            build = abi_build
    return build

def test_new(build_no, tl_index=1):
    abi_build = "abi_build"
    a, b = abi_build, build_no
    (a, b) = (a, b) if (build_no.startswith('TL') or 'TDD' in build_no) else (b, a)
    build = a if tl_index == 1 else b
    return build

print test('TL00_1208_1145')==test_new('TL00_1208_1145')
print test('SBTSTDD_1219_1432') == test_new('SBTSTDD_1219_1432')
print test('TL00_1208_1145', 2)==test_new('TL00_1208_1145', 2)
print test('SBTSTDD_1219_1432', 2) == test_new('SBTSTDD_1219_1432', 2)

print test('FL00_1208_1145')==test_new('FL00_1208_1145')
print test('SBTSFDD_1219_1432') == test_new('SBTSFDD_1219_1432')
print test('FL00_1208_1145', 2)==test_new('FL00_1208_1145', 2)
print test('SBTSFDD_1219_1432', 2) == test_new('SBTSFDD_1219_1432', 2)

True
True
True
True
True
True
True
True


In [5]:
class PM(object):

    def _setup(self):
        print 'pm setup'

    def get(self):
        print 'pm get function'

    def pm_keyword(self):
        self._setup()

class CM(object):

    def _setup(self):
        print 'cm setup'

    def get(self):
        print 'cm get function'

    def cm_keyword(self):
        CM._setup(self)


class SM(object):
 
    def _setup(self):
        print 'SM setup'

    def get(self):
        print 'SM get function'

    def sm_keyword(self):
        self._setup()
        
class interface(SM, CM, PM): #multiple inherit need take care of the same name function
    pass

interface().cm_keyword()

 


    
    




cm setup
